Feat: 오류 제보 퍼블리싱
TEAM-UNITRIP/UNITRIP-FrontEnd pull request #32
Opened 2024-09-05 18:25 UTC by doyn511

close #issue_number

<br />

## ✅ 완료 태스크
- 오류 제보 플로우와 관련된 뷰 퍼블리싱
- 토스트 메시지 공통 컴포넌트 분리

<br />

## 🔎 PR 내용
```
// Explanation.tsx

  const onChangeInput = _.debounce(
    (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      handleSetErrorContent(e.target.value);
      handleSetIsActive(e.target.value.trim().length);
    },
    300,
  );
```
- 글자수에 따른 버튼의 활성화 여부를 처리하기 위해 `onChangeInput` 함수를 만들었는데요.. onChange 될 때마다 실행되는건 성능상 좋지 않기에 debounce를 한번 사용해보았습니다. 
- `debounce` : 연속적으로 발생한 이벤트를 하나로 처리하는 방식으로 주로 처음이나 마지막으로 실행된 함수만을 실행함
- 따라서 마지막으로 입력 이벤트가 있는 뒤, 0.3초 뒤에 state 변경이 이루어지도록 해두었습니다. 

<br />

```
// 공통 컴포넌트, ToastMessage.tsx
const ToastMessage = (props: ToastMessageProps) => {
  const { children, setToast } = props;

  useEffect(() => {
    const timer = setTimeout(() => {
      setToast(false);
    }, 3000);
    return () => {
      clearTimeout(timer);
    };
  }, [setToast]);

  return (
    <div css={toastMessageContainer}>
      <CheckFilledYellowIcon />
      <span>{children}</span>
    </div>
  );
};
```
- 리뷰 작성 플로우에서도 토스트 메시지가 쓰이기에 공통으로 빼두었습니다! 필요하다면 사용되는 뷰에서 토스트 관리하는 state 만드신 뒤에 가져다 쓰시면 될 것 같아용

적용 예시
``` 
const Complete = () => {
  const [toast, setToast] = useState(true);

  return (
    <div css={completeContainer}>
     

        <div css={bottomContainer}>
          {toast && (
            <ToastMessage
              setToast={() => {
                setToast;
              }}>
              등록이 완료되었습니다.
            </ToastMessage>
          )}
          <button type="button" css={button} onClick={() => navigate(-1)}>
            확인
          </button>
        </div>
      </div>
    </div>
  );
};

<br />

## 📷 스크린샷
[ 오류 타입 선택 ]
<img width="373" alt="스크린샷 2024-09-06 오전 2 39 33" src="https://github.com/user-attachments/assets/5ebe07a5-d25b-4487-950c-c2d222edbbb7"><img width="373" alt="스크린샷 2024-09-06 오전 2 46 23" src="https://github.com/user-attachments/assets/9bfe0338-3c41-4b47-ba05-b74518761fe5">

<br />

[ 내용 작성 ]
<img width="373" alt="스크린샷 2024-09-06 오전 2 59 17" src="https://github.com/user-attachments/assets/42fa0dbb-e6e3-474a-915d-1921ac4bd73c"><img width="373" alt="스크린샷 2024-09-06 오전 2 59 52" src="https://github.com/user-attachments/assets/b2edaa7c-7e6f-4be5-8c90-5a106d448bb3">

<br />

[ 완료 ]
<img width="373" alt="스크린샷 2024-09-06 오전 3 00 14" src="https://github.com/user-attachments/assets/0d02ed9e-0c68-4524-b5d6-af8fabd639be">

<br />

[ 전체 플로우 ]
https://github.com/user-attachments/assets/e14d36e7-7a93-45e4-a6a8-4bb4fde8715e

2024-09-12 06:32 UTC, aazkgh requested changes
퍼블리싱 코드 자체는 다 괜찮은 거 같습니당 ㅎㅎ

다만, asset icon들 파일을 찾기가 어려운데 파일 올라갔는지 한 번 확인해주세요..!!
asset 확인해주시면 로컬에서 한 번 더 돌려볼게요

2024-09-12 06:32 UTC, aazkgh commented on src/views/ErrorReport/components/ReportType.tsx
> +import { CheckEmptyIcon, CheckFilledIcon, HeaderBackIcon } from '@/assets/icon';
로컬에서 돌려보니까 `asset`에 이 세 아이콘이 추출 안 되어있다고 뜨더라구요
혹시 아이콘 파일 존재하는지 한 번 부탁드릴게용

2024-09-12 06:42 UTC, doyn511 commented on src/views/ErrorReport/components/ReportType.tsx
> +import { CheckEmptyIcon, CheckFilledIcon, HeaderBackIcon } from '@/assets/icon';
요거 이전 PR에 있는 아이콘들과 동일해서 이번 PR엔 안올렸던 건데요 ..! 이전 PR 머지되어서 다시 pull 받아와 반영시켜두었습니다!

2024-09-12 08:16 UTC, aazkgh approved these changes
수고했어용
퍼블리싱의 끝이 보인다💞

2024-09-13 01:36 UTC, doyn511 commented on src/views/ErrorReport/components/Explanation.tsx
> +          <textarea
반영 완~

2024-09-13 01:37 UTC, doyn511 commented on src/views/ErrorReport/components/Explanation.tsx
> +    300,
반영 완!

2024-09-13 02:08 UTC, aazkgh commented on src/views/ErrorReport/components/Explanation.tsx
> +          <textarea
굿굿 완전 조아염~>><

2024-09-13 02:36 UTC, merged