Feat: 검색 페이지 외 로딩 추가
TEAM-UNITRIP/UNITRIP-FrontEnd pull request #85
Opened 2024-10-07 14:13 UTC by aazkgh

close #79 

<br />

## ✅ 완료 태스크
- 메인/마이 페이지 로딩 추가
- 상세 페이지 첫로딩 및 각 탭별 로딩 추가

<br />

## 🔎 PR 내용

로딩 추가했습니다! 목록 보고 빠진 데 있음 말해주세욤

2024-10-09 08:16 UTC, seobbang requested changes
- [마이페이지-저장한 여행지 목록] 지금은 아무것도 없을 때 뷰가 한번 렌더링되고 깜빡이네용! 여기도 로딩처리로 바꿔주시면 좋을 것 같아요 ㅎㅎ
- [상세페이지] 페이지 로딩 처리해놓으신거 보니까 뭔가 아예 페이지가 꽉 막히는 느낌이 개인적으로 ux 가 좋지 않다고 느껴져서, 탭 이동시에 생기는 것처럼 아래쪽만 로딩 처리 넣어주는게 더 좋을 것 같다는 의견이에요!

2024-10-10 09:23 UTC, aazkgh commented
@seobbang 

> * [상세페이지] 페이지 로딩 처리해놓으신거 보니까 뭔가 아예 페이지가 꽉 막히는 느낌이 개인적으로 ux 가 좋지 않다고 느껴져서, 탭 이동시에 생기는 것처럼 아래쪽만 로딩 처리 넣어주는게 더 좋을 것 같다는 의견이에요!

상세페이지에서 로딩을 추가하는 방식 말고 `-`로 기본값 줬다가 데이터가 오면 변경하는 방식으로 해봤는데 어떤가요?
뭔가 사용자가 봤을 때 불편하다고 느껴지면 더 개선할 의향 무조건 있으니까 편하게 말씀해주세용 ㅎㅎ

이렇게 한 이유
1. 탭보다 위에 상단 화면에서 이미지 및 기본 정보를 불러올 때에는 로딩처리하기가 애매 -> `-`와 썸네일 이미지 활용
2. 최상위 페이지 컴포넌트에서 상세정보 컴포넌트까지 props drilling 최소 세개를 거쳐야함
3. 한 화면에 3~5개 정도의 로딩 컴포넌트가 생각보다 정신 없어보임

2024-10-11 00:40 UTC, seobbang commented
@aazkgh 너무 좋습니당 👍👍

2024-10-11 00:40 UTC, seobbang approved these changes

2024-10-11 06:00 UTC, merged